# Baseline Marian Model Training Configuration with COMET
# This configuration trains a custom Marian model from scratch using COMET evaluation
# Uses RichNachos/georgian-corpus-tokenizer-test for tokenization

# Model configuration
model:
  type: "marian_custom"  # Use custom Marian architecture

  # Model architecture parameters
  architecture:
    d_model: 512
    encoder_layers: 6
    decoder_layers: 6
    encoder_ffn_dim: 2048
    decoder_ffn_dim: 2048
    encoder_attention_heads: 8
    decoder_attention_heads: 8
    dropout: 0.1
    activation_function: "swish"

  # Generation configuration
  generation_config:
    max_length: 128
    num_beams: 1
    early_stopping: true
    do_sample: false

# Data configuration
data:
  max_length: 128
  source_column: "en"
  target_column: "ka"
  target_prefix: ""

# Trainer configuration
trainer:
  type: "seq2seq_with_metrics"

  # Training parameters
  training:
    num_epochs: 10
    train_batch_size: 32
    eval_batch_size: 32
    gradient_accumulation_steps: 1

    # Learning rate and optimization
    learning_rate: 5e-4
    lr_scheduler_type: "cosine"
    warmup_ratio: 0.1
    weight_decay: 0.01

    # Evaluation and logging
    evaluation_strategy: "steps"
    eval_steps: 500
    logging_steps: 100
    save_steps: 500
    save_total_limit: 3

    # Other parameters
    fp16: true
    num_workers: 4
    seed: 42

    # Best model tracking - using COMET as the main metric
    metric_for_best_model: "eval_georgian_comet_comet"
    greater_is_better: true

    # Label smoothing
    label_smoothing_factor: 0.1

    # Reporting
    report_to: "wandb"

    # Early stopping
    early_stopping:
      enabled: true
      patience: 3
      threshold: 0.001

    # Prediction logging
    prediction_logging:
      enabled: true
      num_samples: 20
      frequency: 2

  # Generation parameters for evaluation
  generation:
    max_length: 128
    num_beams: 1
    eval_num_beams: 5

  # Evaluation metrics - Only SacreBLEU, chrF++, and Georgian COMET
  evaluation:
    evaluators:
      - name: "sacrebleu"
        config: {}
      - name: "chrf"
        config:
          word_order: 2  # chrF++
      - name: "georgian_comet"
        config:
          model_name: "Darsala/georgian_comet"  # Your fine-tuned Georgian COMET model
          batch_size: 16
          device: "cuda"
          gpus: 1

# Experiment metadata
experiment:
  name: "baseline_marian_with_comet"
  description: "Baseline Marian model with Georgian COMET evaluation - uses RichNachos tokenizer"
  tags: ["baseline", "marian", "custom", "comet", "georgian"]