# Data Preprocessing and Augmentation Configuration
# Configure which preprocessing and augmentation functions to apply

# Preprocessing functions modify existing data in-place
preprocessors:
  # Normalize various Unicode characters to standard ASCII
  - name: "normalize_characters"
    enabled: true
    description: "Standardize dashes, apostrophes, and quotation marks"
    params:
      columns: ["en", "ka"]

  # Remove extra whitespaces and normalize spacing
  - name: "remove_extra_whitespaces"
    enabled: true
    description: "Clean up spacing and remove extra whitespace"
    params:
      columns: ["en", "ka"]

  # Convert British English to American English
  - name: "convert_to_american"
    enabled: true
    description: "Convert British English words to American equivalents"
    params:
      columns: ["en"]

  # Convert English text to lowercase
  - name: "lowercase_english"
    enabled: true
    description: "Convert English text to lowercase (good for EN→KA)"
    params:
      columns: ["en"]
      preserve_proper_nouns: true

  # Synchronize punctuation between English and Georgian
  - name: "sync_punctuation"
    enabled: true
    description: "Ensure punctuation consistency between EN and KA"
    params:
      strategy: "add_missing"  # 'add_missing' or 'remove_all'
      punctuation_marks: ".!?;:"

  # Remove content within brackets
  - name: "remove_brackets_content"
    enabled: false
    description: "Remove editorial notes and references in brackets"
    params:
      columns: ["en", "ka"]
      bracket_types: ["()"]  # ["()", "[]", "{}", "<>"]

  # Concatenate multiple rows to create longer texts
  - name: "concatenate_long_texts"
    enabled: true
    description: "Concatenate rows to create longer texts for better positional embeddings"
    params:
      concatenation_ratio: 0.2    # 20% of rows will be part of concatenations
      min_group_size: 2           # Minimum rows to concatenate together
      max_group_size: 4           # Maximum rows to concatenate together
      separator: " "              # Separator between concatenated texts
      strategy: "consecutive"     # 'consecutive' or 'random'

  # Fix encoding issues
  - name: "fix_encoding_issues"
    enabled: true
    description: "Fix common encoding problems and special characters"
    params:
      columns: ["en", "ka"]

# Augmentation functions create new data rows
augmenters:
  # Concatenate multiple rows to create longer texts (dataset restructuring)
  - name: "concatenate_long_texts"
    enabled: true
    description: "Concatenate rows to create longer texts for better positional embeddings"
    params:
      concatenation_ratio: 0.2    # 20% of rows will be part of concatenations
      min_group_size: 2           # Minimum rows to concatenate together
      max_group_size: 4           # Maximum rows to concatenate together
      separator: " "              # Separator between concatenated texts
      strategy: "consecutive"     # 'consecutive' or 'random'

  # Add synthetic noise for robustness
  - name: "synthetic_noise"
    enabled: true
    description: "Add character-level noise to improve robustness"
    params:
      percentage: 0.05        # 5% of examples
      noise_types: ["delete", "insert", "substitute", "swap"]
      char_ranges: ["a-z", "A-Z", "ა-ჰ"]
      target_column: "en"     # Apply noise to English

  # Concatenate consecutive sentences
  - name: "sentence_concatenation"
    enabled: true
    description: "Create longer examples by concatenating sentence pairs"
    params:
      percentage: 0.03        # 3% of examples
      separator: " "

  # Reverse word order in sentences
  - name: "sentence_reversal"
    enabled: false
    description: "Reverse word order for robustness training"
    params:
      percentage: 0.01
      target_column: "ka"

  # Replace words with random alternatives
  - name: "random_word_replacement"
    enabled: false
    description: "Replace aligned words with random alternatives"
    params:
      percentage: 0.02
      lexicon: {}             # EN-KA word mapping

  # Generate number copying examples
  - name: "number_copying"
    enabled: true
    description: "Generate examples to teach number copying"
    params:
      num_examples: 5_000
      number_types: ["integer", "float", "large", "small"]

  # Generate Georgian text copying examples
  - name: "georgian_text_copying"
    enabled: true
    description: "Generate examples where EN equals KA (from dataset Georgian texts)"
    params:
      percentage: 0.01

  # Simulate machine translation artifacts and errors
  - name: "simulate_translation_artifacts"
    enabled: true
    description: "Simulate common machine translation errors for robustness"
    params:
      percentage: 0.02
      artifact_types: ["word_order", "article_errors"]

# Global settings
settings:
  # Random seed for reproducible augmentation
  random_seed: 42

  # Whether to log intermediate results to wandb
  log_samples: true

  # Maximum number of examples to log per function
  max_log_samples: 10

  # Whether to validate data integrity after each step
  validate_steps: true